<!DOCTYPE html>

<html lang="en">
<head>
    <!-- The jQuery library is a prerequisite for all jqSuite products -->
    <script type="text/ecmascript" src="/test/js/jquery.min.js"></script>
    <!--<script type="text/ecmascript" src="http://test.dev/js/jquery.min.js"></script>-->
    <!-- This is the Javascript file of jqGrid -->
    <script type="text/ecmascript" src="/test/js/trirand/jquery.jqGrid.min.js"></script>
    <!--<script type="text/ecmascript" src="http://test.dev/js/trirand/jquery.jqGrid.min.js"></script>-->
    <!-- This is the localization file of the grid controlling messages, labels, etc.
    <!-- We support more than 40 localizations -->
    <script type="text/ecmascript" src="/test/js/trirand/i18n/grid.locale-ru.js"></script>
    <!-- A link to a jQuery UI ThemeRoller theme, more than 22 built-in and many more custom -->
    <link rel="stylesheet" type="text/css" media="screen" href="/test/css/jquery-ui.css" />
    <!-- The link to the CSS that the grid needs -->
    <link rel="stylesheet" type="text/css" media="screen" href="/test/css/trirand/ui.jqgrid.css" />
    <!--<link rel="stylesheet" type="text/css" media="screen" href="/test/css/trirand/ui.jqgrid.css" />-->
    <meta charset="utf-8" />
    <title>jqTreeGrid - Load On Demand - Load all Rows at once collapsed</title>
</head>
<body>

<table id="tree"></table>
<div id="pager"></div>

<script type="text/javascript">
    jQuery(document).ready(function($) {
        jQuery('#tree').jqGrid({
                "width":"780",
                "hoverrows":false,
                "viewrecords":false,
                "gridview":true,
                "mtype": 'POST',
                //"url":"/media/data_menu.json",
                "url":"/menu/menu-data",
                //"url":"/menu/test1",
                "editurl" : "/menu/modify",
                postData: $("#FrmGrid_tree").serialize(),
                "ExpandColumn":"name",
                "height":"auto",
                "sortname":"account_id",
                "scrollrows":true,
                "treeGrid":true,
                "treedatatype":"json",
                "treeGridModel":"adjacency",
                "loadonce":false,
                "rowNum":1000,
                "treeReader":{
                    "parent_id_field":"parent_id",
                    "level_field":"level",
                    "leaf_field":"isLeaf",
                    "expanded_field":"expanded",
                    "loaded":"loaded",
                    "icon_field":"icon"
                },
                "datatype":"json",
                "colModel":[
                    {
                        "name":"account_id",
                        "key":true,
                        "hidden":true
                    },{
                        "name":"name",
                        "label":"Title",
                        "width":170,
                        "editable":true
                    },{
                     "name":"url",
                     "label":"Url",
                     "width":170,
                     "editable":true
                     },{
                     "name":"created",
                     //"sorttype":"date",
                     "label":"Created",
                     "width":90,
                     "formatter": "datetime",
                     //"align":"right",
                     //"editable":true
                     },{
                     "name":"updated",
                     //"sorttype":"numeric",
                     "formatter": "datetime",
                     "label":"Updated",
                     "width":90,
                     //"align":"right",
                     //"editable":true
                     },/*{
                     "name":"balance",
                     "sorttype":"numeric",
                     "formatter": "number",
                     "label":"Balance",
                     "width":90,
                     "align":"right",
                     "editable":true
                     },*/{
                        "name":"parent_id",
                        "hidden":true
                    }
                ],
                "pager":"#pager"
            },
            console.log()
        );
        // nable add
        jQuery('#tree').jqGrid('navGrid','#pager',
            {
                "edit":true,
                "add":true,
                "del":true,
                "search":false,
                "refresh":true,
                "view":false,
                "excel":false,
                "pdf":false,
                "csv":false,
                "columns":false
            },
            {"drag":true,"resize":true,"closeOnEscape":true,"dataheight":150},
            {"drag":true,"resize":true,"closeOnEscape":true,"dataheight":150}
        );
        //jQuery('#tree').jqGrid('bindKeys');
    });
</script>
<!-- End of code related to code tabs -->
</body>
</html>